"""cigar_type veld en smoke_event tabel

Revision ID: fc9b7b1e4fe0
Revises: 5b5db4d0b1bc
Create Date: 2026-03-15 14:49:30.112556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9b7b1e4fe0'
down_revision = '5b5db4d0b1bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smoke_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cigar_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('smoked_at', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigar.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cigar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cigar_type', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cigar', schema=None) as batch_op:
        batch_op.drop_column('cigar_type')

    op.drop_table('smoke_event')
    # ### end Alembic commands ###
